### ISSUE TITLE
Calculation suddenly stops during sTD-DFT procedure, "matrix power impossible"

### ISSUE THREAD

**Issue by brigreens** [grimme-lab/xtb4stda#12]
I am trying to run sTD-DFT-xTB on oligomers and certain ones are crashing. They seem to all stop right after the sTD-DFT procedure begins as it is setting up A+B and A-B matrices. I get the error message "matrix power impossible".  I attached my input xyz file and the stda output file. Any advice would be much appreciated.

[351_414_010101.txt](https://github.com/grimme-lab/xtb4stda/files/8583267/351_414_010101.txt)
[351_414_010101.xyz.txt](https://github.com/grimme-lab/xtb4stda/files/8583268/351_414_010101.xyz.txt)

**Comment by mdewergi** [comment]
This is a problem with TD-DFT itself. When doing such calculation it takes (A-B)^1/2, if you have very small gaps, you have negative values in A-B and thus TD-DFT complex roots that cannot be handle by stda. To avoid this, the only solution is to use TDA unfortunately.

**Comment by mdewergi** [comment]
Sometime increasing the energy threshold solves the problem with  the -e option higher than the default 7 eV one. But I test it here and it does nothing.
