### ISSUE TITLE
Vibronic spectral calculation by sTDA-xTB?

### ISSUE THREAD

**Issue by proexcuse** [grimme-lab/xtb4stda#14]
Hello,
Thank you for developing this great package. 

I'd like to request a feature to compute vibronic spectra by sTDA-xTB for fast prediction of absorption spectral shape. 

As implemented in Gaussian, vertical gradient model is desirable to compute fast. Vertical hessian or adiabatic hessian is another option, but may be computationally-expensive.

**Comment by mdewergi** [comment]
Hi, this is planned for the future but do not expect to see it anytime soon.
I have applied for fundings to have one postdoc doing the job. If granted, this should be available in a couple of years.
