### ISSUE TITLE
MKL error with a large number of atoms

### ISSUE THREAD

**Issue by pierre-24** [grimme-lab/xtb4stda#3]
**Describe the bug**
While running `xtb4stda` on a large number of atoms, I encountered an error:

```
Intel MKL ERROR: Parameter 11 was incorrect on entry to DSYGVD.
diag error
```

**To Reproduce**

I'm working on a freshly compiled version of `xtb4stda`, but it was already the case on a older (?) version compiled and provided by @mdewergi. 

I cannot disclose the system on which this error happened (especially since it is not mine), so I reproduced it by incrementally adding methane molecule.  I didn't use solvent.

`xtb4stda` is ok with 1170 methane molecules (5850 atoms):

```
 --------------------------------------------
          xTB calculation for sTDA...
 --------------------------------------------
 
 reading parameter file 
 /home/pbeaujea/bin/.xtb-all//share/xtb4stda/.param_stda2.xtb
 
      method parameters     
 k(s)        :  1.6000
 k(p)        :  2.1800
 k(d)        :  1.9500
 k(f)        :  2.0000
 k(R-V)      :  2.2750
 k(R-R)      :  1.7650
 Tscal       :  0.2580
 Gscal       :  1.0000
 fpol        :  1.0000
 Zcnf        :  0.3430
 Zqf         :  0.0000
 kcn         :  2.7000
 Ryd Hsplit  :  0.7000
 lshift(virt):  3.1000
 lshift(OS)  :  0.2000
 wllscaling  :  2.6000
 
 mowrcut     : 3.000
 
  Z AO/shell   Hii/eV     exponent
  1     Sun Feb 14 09:53:25 CET 2016    EN: 2.327 GAM: 0.473  GM3: 0.0000
     1s    -14.339618    1.220000
     2sp    -3.348946    0.600000
  6     Sun Feb 14 09:53:25 CET 2016    EN: 2.731 GAM: 0.422  GM3: 0.0000
     2s    -22.009312    1.565095
     2p    -13.020408    1.596905
     3sp    -3.914040    0.824500
 
 Nbf   :        32760
 T(el) :     0.0
 calculating S/T integrals ...
 cpu time for ints    315.314927000000     
 Nao   :        32760
 making H0...
 making H1...
 cpu time for H       98.6259709999995     
 solving ...
 cpu time for diag    57505.5604380000     
 
 gap (eV)           :  14.022
 Koopmans IP (eV)   :  20.172
 Eel (Eh)           : -7653.348973

          eigenvalues
 #    :        4668       4669       4670       4671       4672       4673       4674       4675
 occ. :        2.000      2.000      2.000      2.000      2.000      2.000      2.000      2.000
 eps  :       -20.180    -20.180    -20.179    -20.179    -20.179    -20.178    -20.177    -20.177
 #    :        4676       4677       4678       4679       4680       4681       4682       4683
 occ. :        2.000      2.000      2.000      2.000      2.000      0.000      0.000      0.000
 eps  :       -20.177    -20.176    -20.176    -20.175    -20.174     -6.151     -6.091     -6.090
 #    :        4684       4685       4686       4687       4688       4689       4690       4691
 occ. :        0.000      0.000      0.000      0.000      0.000      0.000      0.000      0.000
 eps  :        -6.082     -6.032     -6.026     -6.024     -6.023     -6.021     -6.005     -5.967
                            1  SCC done.
 writing mo output ...
 molden style : F
 
speedup  3.90
cpu  time for all   17 h 36 m 30.9 s
wall time for all    4 h 31 m  8.8 s
```

But it is failing with 1180 methane molecules (5900 atoms):

```
 --------------------------------------------
          xTB calculation for sTDA...
 --------------------------------------------
 
 reading parameter file 
 /home/pbeaujea/bin/.xtb-all//share/xtb4stda/.param_stda2.xtb
 
      method parameters     
 k(s)        :  1.6000
 k(p)        :  2.1800
 k(d)        :  1.9500
 k(f)        :  2.0000
 k(R-V)      :  2.2750
 k(R-R)      :  1.7650
 Tscal       :  0.2580
 Gscal       :  1.0000
 fpol        :  1.0000
 Zcnf        :  0.3430
 Zqf         :  0.0000
 kcn         :  2.7000
 Ryd Hsplit  :  0.7000
 lshift(virt):  3.1000
 lshift(OS)  :  0.2000
 wllscaling  :  2.6000
 
 mowrcut     : 3.000
 
  Z AO/shell   Hii/eV     exponent
  1     Sun Feb 14 09:53:25 CET 2016    EN: 2.327 GAM: 0.473  GM3: 0.0000
     1s    -14.339618    1.220000
     2sp    -3.348946    0.600000
  6     Sun Feb 14 09:53:25 CET 2016    EN: 2.731 GAM: 0.422  GM3: 0.0000
     2s    -22.009312    1.565095
     2p    -13.020408    1.596905
     3sp    -3.914040    0.824500
 
 Nbf   :        33040
 T(el) :     0.0
 calculating S/T integrals ...
 cpu time for ints    320.219369000000     
 Nao   :        33040
 making H0...
 making H1...
 cpu time for H       141.714109000000     
 solving ...

Intel MKL ERROR: Parameter 11 was incorrect on entry to DSYGVD.
diag error
```

According to my research, it seems related to a to large integer (I don't know the equivalent in Fortran) that overflows (the number is too large for the number of bits available for that type, or something like that). But my BLAS is a bit rusty (and I never used it directly).

It is probably related to the number of basis functions more than to the number of atoms, though (the actual system on which this error happened for the first time contains a little bit less atoms than that, but way more carbons).

A [gist containing the two inputs and outputs is available](https://gist.github.com/pierre-24/f9cc810e6b2eeb652e77107acb4e7a40).

**Expected behaviour**
The calculation succeed.

**Additional context**
With more than 10 000 atoms, the program outputs that it cannot continue, so a quick (and dirty) fix would be to decrease this limit :/

**Comment by awvwgk** [comment]
Oh, you are running into numerical precision problems here. The integer overflow happens for the size of the work space, see [argument 11 (`LWORK`)](https://www.netlib.org/lapack/explore-html/d2/d8a/group__double_s_yeigen_ga912ae48bb1650b2c7174807ffa5456ca.html). The size used is `lwork = 1 + 6*nbf + 2*nbf**2` which overflows for 33040 basis functions in 32 bit signed integer range.

The [MKL link line advisor](https://software.intel.com/en-us/articles/intel-mkl-link-line-advisor) suggests to change `mkl_intel_lp64` to `mkl_intel_ilp64` and add `-i8` to the compiler arguments. This will result in 64 bit signed integer range and should suffice (at least within the hard coded range of this program).

**Comment by awvwgk** [comment]
@mdewergi Is this a bug? I'm not sure how we should deal with this kind of numerical issues. Compiling with 64 bit integer range by default might be overkill, but we might document this failure and a workaround for future reference.

On a related note, if it fails here due to numerics, it might also fail in `stda` due to similar issues.

**Comment by pierre-24** [comment]
It might definitely be an issue on (for example) large proteins, since it is related to (like I thought) basis functions. I would at least favour a workaround (I don't know exactly what going fully 64bits integers implies, but it might affect the memory usage significantly if you store an array of integer somewhere).

**Comment by mdewergi** [comment]
Here putting all integer in 64 bit is not the best way to go because it will unnecessarily enlarged memory usage but it is an easy workaround that @pierre-24 you should test. Here, one needs to put in double precision variables needed like lwork, liwork,... though it is very possible that we will encounter other problems after. On the top of this, it is likely that if we can make xtb4stda working for this issue, then stda will not be able to run for the same reason plus memory usage... @pierre-24 if the workaround is working can you try to run stda to see if it is just able to do it? @awvwgk a bug no but an issue yes and definitively this should be documented...

**Comment by awvwgk** [comment]
Just added a new option for the interface, like it is called in the link line advisor, to the meson build-file. For the make based build I left instructions in the README under *known issues* (all the way on the bottom, maybe not the best place).
