### ISSUE TITLE
Crash on multiple machines

### ISSUE THREAD

**Issue by RaphaelRobidas** [grimme-lab/xtb4stda#6]
xtb4stda crashes on our workstation (Ryzen 9 3950X running Ubuntu 18) and on our clusters (Intel Xeon E5462 or AMD Opteron 6172 running CentOS 5.5 and 6.5). However, xtb4stda works on my personal machine (Intel i7 9900 running Debian 10). The "standard" xtb works on all machines.

The bug occurs while executing "xtb4stda coord.xyz". Any valid .xyz file will cause a crash (ex. propane). The program crashes with the following error:

```
forrtl: severe (8): internal consistency check failure, file for_intrp_fmt.c, line 2745
Image              PC                Routine            Line        Source             
xtb4stda           00000000014B29CC  Unknown               Unknown  Unknown
xtb4stda           0000000001450B11  Unknown               Unknown  Unknown
xtb4stda           000000000144FAB0  Unknown               Unknown  Unknown
xtb4stda           000000000043D862  Unknown               Unknown  Unknown
xtb4stda           0000000000408A89  Unknown               Unknown  Unknown
xtb4stda           000000000040205E  Unknown               Unknown  Unknown
xtb4stda           00000000015F3720  Unknown               Unknown  Unknown
xtb4stda           0000000000401F47  Unknown               Unknown  Unknown
```

I recompiled the program on the workstation in debug mode. The same error occurs, but the error message is a bit more descriptive:

```
forrtl: severe (408): fort: (2): Subscript #1 of the array TIMESTP has value 98 which is greater than the upper bound of 94

Image              PC                Routine            Line        Source             
xtb4stda           00000000015C0A7F  Unknown               Unknown  Unknown
xtb4stda           00000000004A5B6C  rdelparam_                165  readparam.f
xtb4stda           0000000000407F10  MAIN__                    342  main.f
xtb4stda           0000000000400DD2  Unknown               Unknown  Unknown
xtb4stda           00000000017BACA9  Unknown               Unknown  Unknown
xtb4stda           0000000000400CAA  Unknown               Unknown  Unknown
```

I hope this is useful to you!

**Comment by awvwgk** [comment]
Strange, looks like an out-of-bounds error in the reading routine for the sTDA-xTB parameter file. `xtb4stda` reads the atomic number directly from the `$Z=<num>` field in the `.param_stda{1,2}.xtb` file, the atomic number corresponds to the internal storage location where the timestamp is written to. The upper bound of the parameter arrays is 94, here we apparently want to write at 98, which is, of course, out-of-bounds.

Could you verify that your parameter file does not contain any `$Z=98` for any particular reason?
@mdewergi could you help investigating here?

**Comment by RaphaelRobidas** [comment]
Oops, it was actually my fault. You are indeed correct and the .param_stdaX.xtb were totally wrong: I must have used the wrong url to wget them (twice!) and it gave me HTML files. With the actual parameter files, everything seems to work.

Sorry for the trouble!

**Comment by awvwgk** [comment]
Adding a raw in the path for `wget` tells GH to provide you with the actual file instead of its HTML view:
https://github.com/grimme-lab/xtb4stda/raw/master/.param_stda1.xtb
